type = "file"
name = "AlibabaBlock"
capacities = [ 10_000, 20_000, 30_000, 40_000, 50_000, 60_000, 70_000, 80_000 ]
caches = [
    "otter",
    "xsync",
    "pb"
]

[file]
trace_type = "oracleGeneral"
paths = [ "trace/oracleGeneral/io_traces.ns49.oracleGeneral.zst" ]
