type = "file"
name = "Twitter"
capacities = [ 250, 500, 750, 1000, 1250, 1500, 1750, 2000 ]
caches = [
    "otter",
    "xsync",
    "pb"
]

[file]
trace_type = "oracleGeneral"
paths = [ "trace/oracleGeneral/cluster24.oracleGeneral.sample10.zst" ]
